In [3]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [6]:
# 2. Print the NUMPY version and the configuration.
print("NumPy Version:", np.__version__)
print("NumPy Configuration:")
print(np.show_config())

NumPy Version: 1.26.4
NumPy Configuration:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4408414224
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong, -O2, -pipe, -isystem,
      /opt/anaconda3/include, -fdebug-prefix-map=/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_a51i_mbs7m/croot/numpy_and_numpy_base_1708638620867/work=/usr/local/src/conda/numpy-base-1.26.4,
      -fdebug

In [8]:
# 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
a = np.random.random((2, 3, 5))

# 4. Print a.
print("Array a:\n", a)

Array a:
 [[[0.89954718 0.74019207 0.92837862 0.64565576 0.6154871 ]
  [0.5189409  0.59590468 0.38179435 0.6401807  0.97877192]
  [0.06641084 0.37600692 0.0574289  0.49661098 0.16035803]]

 [[0.57764584 0.43334498 0.39249701 0.36964326 0.71192014]
  [0.95919928 0.39938721 0.56075441 0.47385908 0.28967461]
  [0.14435921 0.58033138 0.73943096 0.71174968 0.06691934]]]


In [10]:
# 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
b = np.ones((5, 2, 3))

# 6. Print b.
print("Array b:\n", b)

# 7. Do a and b have the same size? How do you prove that in Python code?
print("Do a and b have the same size?", a.size == b.size)

Array b:
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
Do a and b have the same size? True


In [12]:
# 8. Are you able to add a and b? Why or why not?
# No, because they do not have the same shape and thus cannot be broadcast together for addition.

# 9. Transpose b so that it has the same structure of a (i.e., become a 2x3x5 array). Assign the transposed array to variable "c".
c = np.transpose(b, (1, 2, 0))

# 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?
d = a + c  # Works because c is now the same shape as a.

# 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print("Array a:\n", a)
print("Array d:\n", d)  # d should be a with 1 added to each element.

Array a:
 [[[0.89954718 0.74019207 0.92837862 0.64565576 0.6154871 ]
  [0.5189409  0.59590468 0.38179435 0.6401807  0.97877192]
  [0.06641084 0.37600692 0.0574289  0.49661098 0.16035803]]

 [[0.57764584 0.43334498 0.39249701 0.36964326 0.71192014]
  [0.95919928 0.39938721 0.56075441 0.47385908 0.28967461]
  [0.14435921 0.58033138 0.73943096 0.71174968 0.06691934]]]
Array d:
 [[[1.89954718 1.74019207 1.92837862 1.64565576 1.6154871 ]
  [1.5189409  1.59590468 1.38179435 1.6401807  1.97877192]
  [1.06641084 1.37600692 1.0574289  1.49661098 1.16035803]]

 [[1.57764584 1.43334498 1.39249701 1.36964326 1.71192014]
  [1.95919928 1.39938721 1.56075441 1.47385908 1.28967461]
  [1.14435921 1.58033138 1.73943096 1.71174968 1.06691934]]]


In [14]:
# 12. Multiply a and c. Assign the result to e.
e = a * c

# 13. Does e equal to a? Why or why not?
print("Does e equal to a?", np.array_equal(e, a))  # Yes, because multiplying by 1 does not change the values.

# 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean".
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

# 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e., 2x3x5) as d using `np.empty`.
f = np.empty_like(d)

Does e equal to a? True


In [16]:
# 16. Populate the values in f.
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] < d_mean:
                if d[i, j, k] == d_min:
                    f[i, j, k] = 0
                else:
                    f[i, j, k] = 25
            elif d[i, j, k] > d_mean:
                if d[i, j, k] == d_max:
                    f[i, j, k] = 100
                else:
                    f[i, j, k] = 75
            else:
                f[i, j, k] = 50

# 17. Print d and f.
print("Array d:\n", d)
print("Array f:\n", f)

# 18. Bonus question: Using string values to label the array elements.
labels = np.empty(d.shape, dtype=str)
labels[f == 0] = 'A'
labels[f == 25] = 'B'
labels[f == 50] = 'C'
labels[f == 75] = 'D'
labels[f == 100] = 'E'

print("Labeled array with string values:\n", labels)

Array d:
 [[[1.89954718 1.74019207 1.92837862 1.64565576 1.6154871 ]
  [1.5189409  1.59590468 1.38179435 1.6401807  1.97877192]
  [1.06641084 1.37600692 1.0574289  1.49661098 1.16035803]]

 [[1.57764584 1.43334498 1.39249701 1.36964326 1.71192014]
  [1.95919928 1.39938721 1.56075441 1.47385908 1.28967461]
  [1.14435921 1.58033138 1.73943096 1.71174968 1.06691934]]]
Array f:
 [[[ 75.  75.  75.  75.  75.]
  [ 75.  75.  25.  75. 100.]
  [ 25.  25.   0.  25.  25.]]

 [[ 75.  25.  25.  25.  75.]
  [ 75.  25.  75.  25.  25.]
  [ 25.  75.  75.  75.  25.]]]
Labeled array with string values:
 [[['D' 'D' 'D' 'D' 'D']
  ['D' 'D' 'B' 'D' 'E']
  ['B' 'B' 'A' 'B' 'B']]

 [['D' 'B' 'B' 'B' 'D']
  ['D' 'B' 'D' 'B' 'B']
  ['B' 'D' 'D' 'D' 'B']]]
